# Generated by Django 3.1.1 on 2020-09-26 12:05

from django.db import migrations


def create_data(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    Customer(first_name='Customer_001', last_name='Customer_001', email='customr001@mail.com',
             phone='00000000', address='Customer 001 Address',
             description='Customer 001 description').save()


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
